<a href="https://colab.research.google.com/github/chandupriya1206/Movie-Recomendation/blob/main/AI_proj.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

IMPORTING THE NECESSARY LIBRARIES AND THE FUNCTIONS WE NEED TO THIS PROJECT



In [ ]:
import numpy as np
import pandas as pd
import difflib # we use this library to get the closest match of the movie from the available data set for the name entered by the user .
from sklearn.feature_extraction.text import TfidfVectorizer # here TEXTUAL data is converted into numerical data
from sklearn.metrics.pairwise import cosine_similarity # gives the highest similarity score,based on this score we recommend movies.

Data Collection and Pre-Processing

In [ ]:
# loading the data from the csv file to a pandas dataframe
movies_data = pd.read_csv('/content/drive/MyDrive/AI proj data set/movies.csv')

In [ ]:
# printing the first 5 rows of the dataframe
movies_data.head()

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [ ]:
# To know how many number of rows and columns are present in the data frame
movies_data.shape

(4803, 24)

In [ ]:
# selecting the relevant features for recommendation

req_features = ['genres','keywords','tagline','cast','director','overview']
print(req_features)

['genres', 'keywords', 'tagline', 'cast', 'director', 'overview']


In [ ]:
# replacing the null valuess with null string

for feature in req_features:
  movies_data[feature] = movies_data[feature].fillna('')

In [ ]:
# combining all the 6 selected features to the total_combined_features variable.

total_combined_features = movies_data['genres']+' '+movies_data['keywords']+' '+movies_data['tagline']+' '+movies_data['cast']+' '+movies_data['director']+' '+movies_data['overview']

In [ ]:
# printing all the values present in total_combined_features
print(total_combined_features)

0       Action Adventure Fantasy Science Fiction cultu...
1       Adventure Fantasy Action ocean drug abuse exot...
2       Action Adventure Crime spy based on novel secr...
3       Action Crime Drama Thriller dc comics crime fi...
4       Action Adventure Science Fiction based on nove...
                              ...                        
4798    Action Crime Thriller united states\u2013mexic...
4799    Comedy Romance  A newlywed couple's honeymoon ...
4800    Comedy Drama Romance TV Movie date love at fir...
4801      A New Yorker in Shanghai Daniel Henney Eliza...
4802    Documentary obsession camcorder crush dream gi...
Length: 4803, dtype: object


In [ ]:
# converting the text data to feature vectors
vector = TfidfVectorizer()

In [ ]:
# fitting the vector data into a feature vector under the variable f_vector
f_vector = vector.fit_transform(total_combined_features)

In [ ]:
# printing the data in f_vector
print(f_vector)

  (0, 5245)	0.16506865163441017
  (0, 1014)	0.12285843797047788
  (0, 1243)	0.05270709034262742
  (0, 21523)	0.16650106431669984
  (0, 1281)	0.0319519027005067
  (0, 19650)	0.16120557402371172
  (0, 10368)	0.138482776543016
  (0, 2974)	0.09974129089792808
  (0, 27515)	0.1456922041909068
  (0, 2685)	0.09805341831299118
  (0, 4129)	0.06195738171764886
  (0, 18025)	0.1093940665047336
  (0, 28597)	0.15490753406550084
  (0, 19541)	0.04908322232312577
  (0, 18249)	0.14769810641761005
  (0, 27405)	0.031015019219557106
  (0, 7827)	0.17979882024342952
  (0, 14023)	0.04170092858483918
  (0, 17021)	0.14324534514274756
  (0, 20104)	0.19260031442011957
  (0, 4768)	0.12501550204808318
  (0, 239)	0.19716936546022965
  (0, 13474)	0.036478409857958735
  (0, 4288)	0.13213124585063998
  (0, 14180)	0.08418056281586365
  :	:
  (4802, 27153)	0.05940079357098276
  (4802, 19243)	0.061349419053434766
  (4802, 11941)	0.07829183421073846
  (4802, 29680)	0.07735547381237222
  (4802, 9346)	0.07104321122746965
  (4

In [ ]:
# getting the similarity scores using cosine similarity
ss = cosine_similarity(f_vector)

In [ ]:
# printing the similarity score data
print(ss)

[[1.         0.05083168 0.0332947  ... 0.02749812 0.0304889  0.0072518 ]
 [0.05083168 1.         0.04356836 ... 0.05077045 0.03100979 0.01521198]
 [0.0332947  0.04356836 1.         ... 0.02646984 0.04751623 0.01372603]
 ...
 [0.02749812 0.05077045 0.02646984 ... 1.         0.03481447 0.03546821]
 [0.0304889  0.03100979 0.04751623 ... 0.03481447 1.         0.03098945]
 [0.0072518  0.01521198 0.01372603 ... 0.03546821 0.03098945 1.        ]]


In [ ]:
#printing the similarity score shape
print(ss.shape)

(4803, 4803)


Getting the movie name from the user

In [ ]:

# Asking the user to input  their favourite name
movie_name = input(' Enter your favourite movie name : ')

 Enter your favourite movie name : jhon carter


In [ ]:
# creating a list with all the movie names given in the dataset

list_all_titles = movies_data['title'].tolist()
print(list_all_titles)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [ ]:
# finding the close match for the movie name given by the user

find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)
print(find_close_match)

['John Carter', 'Songcatcher', 'Coach Carter']


In [ ]:
# printing the most accurate close match which is present at index 0
close_match = find_close_match[0]
print(close_match)

John Carter


In [ ]:
# finding the index of the movie with title

index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values[0]
print(index_of_the_movie)

4


In [ ]:
# getting a list of similar movies

similarity_score = list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)

[(0, 0.08724686630893656), (1, 0.08138487797447401), (2, 0.03571824878321604), (3, 0.030265920951137636), (4, 1.0), (5, 0.07010220294951891), (6, 0.04200339816330223), (7, 0.08511176912180952), (8, 0.02299262730144765), (9, 0.05512045585396982), (10, 0.06660144184460447), (11, 0.03208943158974076), (12, 0.05412403356397667), (13, 0.05458819227069716), (14, 0.08155570443558612), (15, 0.06153139958378848), (16, 0.07911855483427592), (17, 0.06985897896993964), (18, 0.07655447350450878), (19, 0.05368693726713193), (20, 0.0735031404569844), (21, 0.047683552949690455), (22, 0.019526278194134383), (23, 0.03757947427664069), (24, 0.0683620071790332), (25, 0.04396628169123479), (26, 0.08257743155120045), (27, 0.12034490373803816), (28, 0.032410927057040434), (29, 0.046831143789834204), (30, 0.043312883156247935), (31, 0.0576922543218295), (32, 0.08837089246689346), (33, 0.06197434946822362), (34, 0.018264156461320267), (35, 0.04522322702659919), (36, 0.073274868473464), (37, 0.0324456642102126)

In [ ]:
# printing the length of the similarity score
len(similarity_score)

4803

In [ ]:
# sorting the movies based on their similarity score in decending order which is present at 2 nd place in similarity score

sorted_similar_movies = sorted(similarity_score, key = lambda y:y[1], reverse = True)
print(sorted_similar_movies)

[(4, 1.0), (373, 0.17847618351328087), (473, 0.16897167284729728), (270, 0.14455756961868388), (1735, 0.1419407252024897), (207, 0.1328269745695728), (2755, 0.13174572002658946), (2964, 0.12875231609915058), (127, 0.12421301404453107), (487, 0.12181399479238561), (1254, 0.12177486611482172), (27, 0.12034490373803816), (47, 0.11605596737758327), (48, 0.11602922776020667), (85, 0.11526964926097868), (1564, 0.11509641967506334), (3780, 0.11427251613308467), (3445, 0.11312828842991543), (3158, 0.11301533160986502), (3668, 0.11097225863965034), (1057, 0.10940126301628406), (2433, 0.10931193815182955), (889, 0.10924413170534242), (4653, 0.10807988224033949), (3072, 0.10788522393375144), (2904, 0.10625997816574573), (3373, 0.10526784452558936), (46, 0.10448005176846017), (4332, 0.10431277082770689), (870, 0.1022938204335561), (3899, 0.10207734606929468), (1158, 0.10171234201015619), (4161, 0.10091007852574739), (2403, 0.10056885967763887), (1959, 0.1000920143714395), (1373, 0.0996743082164895

In [ ]:
# print the name of similar movies based on the index

print('The recommended movies for you are  : \n')

i = 1

for movie in sorted_similar_movies:
  ind = movie[0]
  title_from_index = movies_data[movies_data.index==ind]['title'].values[0]
  if (i<36):
    print(i, '-',title_from_index)
    i+=1

The recommended movies for you are  : 

1 - John Carter
2 - Mission to Mars
3 - Mars Attacks!
4 - The Martian
5 - Ghosts of Mars
6 - Total Recall
7 - Earth to Echo
8 - The Last Days on Mars
9 - Mad Max: Fury Road
10 - Red Planet
11 - Get Carter
12 - Battleship
13 - Star Trek Into Darkness
14 - Jack the Giant Slayer
15 - Captain America: The Winter Soldier
16 - Legends of the Fall
17 - Poolhall Junkies
18 - Platoon
19 - Alien
20 - Capricorn One
21 - Coach Carter
22 - Superman IV: The Quest for Peace
23 - The Thin Red Line
24 - Rust
25 - Atlas Shrugged Part II
26 - Heaven is for Real
27 - The Other Side of Heaven
28 - X-Men: Days of Future Past
29 - Silent Running
30 - Superman II
31 - Beneath the Planet of the Apes
32 - Lone Survivor
33 - The Marine 4: Moving Target
34 - Aliens
35 - Star Trek IV: The Voyage Home


Movie Recommendation Sytem

In [ ]:
movie_name = input(' Enter your favourite movie name : ')

list_all_titles = movies_data['title'].tolist()

find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)

close_match = find_close_match[0]

index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values[0]

similarity_score = list(enumerate(similarity[index_of_the_movie]))

sorted_similar_movies = sorted(similarity_score, key = lambda y:y[1], reverse = True)

print('The recommended movies for you are  : \n')

i = 1

for movie in sorted_similar_movies:
  ind = movie[0]
  title_from_index = movies_data[movies_data.index==ind]['title'].values[0]
  if (i<25):
    print(i, '-',title_from_index)
    i+=1

 Enter your favourite movie name : tangled
The recommended movies for you are  : 

1 - Tangled
2 - The Black Stallion
3 - The Negotiator
4 - Dreamer: Inspired By a True Story
5 - Enchanted
6 - Hidalgo
7 - The Thief and the Cobbler
8 - Into the Woods
9 - Hansel and Gretel Get Baked
10 - Miss Potter
11 - TRON: Legacy
12 - Puss in Boots
13 - Horse Camp
14 - Last Action Hero
15 - Maleficent
16 - Of Horses and Men
17 - Street Fighter
18 - Roadside Romeo
19 - Racing Stripes
20 - Running Forever
21 - Out of Inferno
22 - The Raid
23 - Shrek 2
24 - The Promise
